#!/usr/bin/env python
import json
import os
from os.path import expanduser,exists

try: raw_input
except NameError: raw_input = input

home_env_path = expanduser('~/.irods')

if not exists(home_env_path):
    os.makedirs(home_env_path)

host = raw_input('irods server host -> ')
port = raw_input('irods server port -> ')
user = raw_input('irods user -> ')
zone = raw_input('irods zone -> ')

json.dump( {
             "irods_host": host,
             "irods_port": int(port),
             "irods_user_name": user,
             "irods_zone_name": zone
           },
           open(expanduser('~/.irods/irods_environment.json'),'w'),
           indent=4
)
