#!/usr/bin/env python

from __future__ import print_function
from irods.session import iRODSSession
from os.path import expanduser
import sys 

from getopt import getopt
opt,arg=getopt(sys.argv[1:],'r')
optD = dict(opt)

with iRODSSession(
     irods_env_file=expanduser('~/.irods/irods_environment.json')) as s:
  if not arg: arg=['/{0.zone}/home/{0.username}'.format(s)]
  collection = s.collections.get(arg[0])
  if '-r' not in optD:
    print('C',collection.path)
  else:
    for this,subcols,dataobjs in collection.walk():
      print('C',this.path)  
      for d in dataobjs:
        print('D',d.path)
