#!/usr/bin/env python
from os.path import expanduser
from getpass import getpass
from irods.password_obfuscation import encode as pw_encode
open(expanduser('~/.irods/.irodsA'),'w').write(
    pw_encode(getpass('irods password ->'))
)
